/* =========================================================================
   BlindSpots 2026 — dataset, part 1 of 2 (professions 1–15).
   Each profession carries 8 statistics. Figures are approximate, rounded,
   and drawn from published research, government data, and industry reports.
   Every entry links to the publishing organization.

   tone: "blind"  = a cost the field rarely talks about
         "bright" = a win the field rarely celebrates
   chart.type: "donut" (single value), "bar", or "line"
   ========================================================================= */

window.BLINDSPOTS = window.BLINDSPOTS || [];

window.BLINDSPOTS.push(
{
  id: "therapist", name: "Therapist / Counselor",
  stats: [
    { t: "The empty chair", tone: "blind",
      s: "About 37.9% of patients in the U.S. do not complete therapy, with most dropouts occurring after the first two sessions.",
      chart: { type: "donut", value: 37.9, unit: "%", caption: "of patients drop out of treatment" },
      src: { n: "Swift & Greenberg, APA Journal of Consulting and Clinical Psychology", u: "https://www.apa.org" } },
    { t: "Care that works", tone: "bright",
      s: "The average person who completes psychotherapy ends up better off than about 80% of untreated people, an effect size on par with many major medical treatments.",
      chart: { type: "donut", value: 80, unit: "%", caption: "of untreated people fare worse than the average treated patient" },
      src: { n: "American Psychological Association, Resolution on Psychotherapy Effectiveness", u: "https://www.apa.org" } },
    { t: "Nobody within reach", tone: "blind",
      s: "More than 120 million Americans live in a federally designated mental health professional shortage area.",
      chart: { type: "bar", unit: "M people", labels: ["In shortage areas", "Rest of U.S."], values: [122, 213], caption: "U.S. population by mental health access" },
      src: { n: "Health Resources & Services Administration (HRSA)", u: "https://data.hrsa.gov" } },
    { t: "Treatment gap", tone: "blind",
      s: "Over half of U.S. adults with a mental illness receive no treatment in a given year.",
      chart: { type: "donut", value: 55, unit: "%", caption: "of adults with mental illness get no treatment" },
      src: { n: "Mental Health America, State of Mental Health in America", u: "https://mhanational.org" } },
    { t: "The therapist matters less than you think", tone: "blind",
      s: "Differences between individual therapists explain only about 5% of patient outcomes; client factors and the relationship explain far more.",
      chart: { type: "bar", unit: "%", labels: ["Therapist effect", "Alliance & client factors"], values: [5, 30], caption: "share of outcome variance" },
      src: { n: "American Psychological Association, Psychotherapy journal", u: "https://www.apa.org" } },
    { t: "Burned out healers", tone: "blind",
      s: "Roughly 45% of psychologists report feeling burned out, and demand has outpaced capacity every year since 2020.",
      chart: { type: "donut", value: 45, unit: "%", caption: "of psychologists reporting burnout" },
      src: { n: "APA Practitioner Pulse Survey", u: "https://www.apa.org" } },
    { t: "The screen works", tone: "bright",
      s: "Meta-analyses find teletherapy outcomes are comparable to in-person care, which has quietly opened treatment to rural and homebound patients.",
      chart: { type: "bar", unit: "effect size", labels: ["In-person", "Telehealth"], values: [0.8, 0.78], caption: "treatment effect, like for like" },
      src: { n: "Journal of Anxiety Disorders / PubMed", u: "https://pubmed.ncbi.nlm.nih.gov" } },
    { t: "Who gets a callback", tone: "blind",
      s: "In an audit study, therapists offered appointments to middle-class white callers nearly 3 times as often as to working-class Black callers.",
      chart: { type: "bar", unit: "%", labels: ["Middle-class white", "Working-class Black"], values: [28, 10], caption: "callers offered an appointment" },
      src: { n: "Kugelmass, Journal of Health and Social Behavior", u: "https://journals.sagepub.com" } }
  ]
},
{
  id: "physician", name: "Physician",
  stats: [
    { t: "Eleven seconds", tone: "blind",
      s: "On average, physicians interrupt a patient's opening statement after just 11 seconds.",
      chart: { type: "bar", unit: "seconds", labels: ["Time before interruption", "Time patients need"], values: [11, 90], caption: "listening time vs. time to tell the story" },
      src: { n: "Journal of General Internal Medicine", u: "https://link.springer.com/journal/11606" } },
    { t: "The third leading cause", tone: "blind",
      s: "Researchers estimate medical error contributes to roughly 250,000 U.S. deaths per year, which would rank behind only heart disease and cancer.",
      chart: { type: "bar", unit: "K deaths/yr", labels: ["Heart disease", "Cancer", "Medical error"], values: [695, 605, 250], caption: "estimated U.S. deaths per year" },
      src: { n: "Johns Hopkins Medicine / BMJ", u: "https://www.hopkinsmedicine.org" } },
    { t: "Misdiagnosed", tone: "blind",
      s: "About 1 in 20 U.S. adults experiences a diagnostic error in outpatient care every year.",
      chart: { type: "donut", value: 5, unit: "%", caption: "of adults misdiagnosed annually" },
      src: { n: "BMJ Quality & Safety", u: "https://qualitysafety.bmj.com" } },
    { t: "Three decades gained", tone: "bright",
      s: "U.S. life expectancy rose from about 47 years in 1900 to nearly 79 today, with medicine and public health driving most of the gain.",
      chart: { type: "line", unit: "years", labels: ["1900", "1950", "1980", "2000", "2023"], values: [47, 68, 74, 77, 78.4], caption: "U.S. life expectancy at birth" },
      src: { n: "CDC National Center for Health Statistics", u: "https://www.cdc.gov/nchs" } },
    { t: "Half the hands", tone: "blind",
      s: "Average hand hygiene compliance in hospitals hovers around 50% of recommended moments, a leading driver of healthcare-associated infections.",
      chart: { type: "donut", value: 50, unit: "%", caption: "average hand hygiene compliance" },
      src: { n: "CDC / World Health Organization", u: "https://www.cdc.gov/handhygiene" } },
    { t: "Vaccines, quietly", tone: "bright",
      s: "Immunization prevents an estimated 4 to 5 million deaths worldwide every single year.",
      chart: { type: "donut", value: 4.5, unit: "M", caption: "deaths prevented per year, worldwide" },
      src: { n: "World Health Organization", u: "https://www.who.int" } },
    { t: "Doctor, heal thyself", tone: "blind",
      s: "Around half of U.S. physicians report at least one symptom of burnout, roughly double the rate of the general workforce.",
      chart: { type: "bar", unit: "%", labels: ["Physicians", "General workforce"], values: [49, 28], caption: "reporting burnout symptoms" },
      src: { n: "Medscape Physician Burnout Report", u: "https://www.medscape.com" } },
    { t: "The coming shortfall", tone: "blind",
      s: "The U.S. faces a projected shortage of up to 86,000 physicians by 2036, hitting rural and primary care hardest.",
      chart: { type: "line", unit: "K shortfall", labels: ["2026", "2030", "2033", "2036"], values: [25, 47, 68, 86], caption: "projected U.S. physician shortage" },
      src: { n: "Association of American Medical Colleges (AAMC)", u: "https://www.aamc.org" } }
  ]
},
{
  id: "nurse", name: "Nurse",
  stats: [
    { t: "One more patient", tone: "blind",
      s: "Each additional patient added to a nurse's workload is associated with a 7% increase in the odds of patient death after common surgery.",
      chart: { type: "bar", unit: "% odds", labels: ["4 patients", "6 patients", "8 patients"], values: [100, 114, 131], caption: "relative odds of 30-day mortality" },
      src: { n: "Aiken et al., JAMA", u: "https://jamanetwork.com" } },
    { t: "America's most trusted", tone: "bright",
      s: "Nurses have ranked as the most honest and ethical profession in America for more than 20 consecutive years of Gallup polling.",
      chart: { type: "bar", unit: "%", labels: ["Nurses", "Doctors", "Clergy", "Bankers"], values: [78, 56, 32, 19], caption: "rated high or very high in honesty" },
      src: { n: "Gallup, Honesty and Ethics of Professions", u: "https://news.gallup.com" } },
    { t: "The exodus", tone: "blind",
      s: "About 100,000 registered nurses left the U.S. workforce during the pandemic, and hundreds of thousands more say they intend to leave by 2027.",
      chart: { type: "bar", unit: "K nurses", labels: ["Left 2020-22", "Intend to leave by 2027"], values: [100, 610], caption: "RN workforce losses, actual and intended" },
      src: { n: "National Council of State Boards of Nursing (NCSBN)", u: "https://www.ncsbn.org" } },
    { t: "Violence on shift", tone: "blind",
      s: "Healthcare workers are about 5 times more likely to suffer a workplace violence injury than workers overall.",
      chart: { type: "bar", unit: "per 10K", labels: ["Healthcare", "All industries"], values: [10.4, 2.1], caption: "intentional injury rate per 10,000 workers" },
      src: { n: "U.S. Bureau of Labor Statistics", u: "https://www.bls.gov" } },
    { t: "Care left undone", tone: "blind",
      s: "In a large European study, 86% of nurses reported leaving at least one necessary care activity undone on their last shift for lack of time.",
      chart: { type: "donut", value: 86, unit: "%", caption: "of nurses leaving care undone per shift" },
      src: { n: "BMJ Quality & Safety, RN4CAST study", u: "https://qualitysafety.bmj.com" } },
    { t: "The back pays the price", tone: "blind",
      s: "Nursing assistants and nurses suffer musculoskeletal injuries at among the highest rates of any U.S. occupation, ahead of construction laborers.",
      chart: { type: "bar", unit: "per 10K", labels: ["Nursing assistants", "Construction", "All workers"], values: [166, 80, 27], caption: "musculoskeletal injury rate" },
      src: { n: "U.S. Bureau of Labor Statistics", u: "https://www.bls.gov" } },
    { t: "Filling the gap", tone: "bright",
      s: "Nurse practitioners now deliver a large share of U.S. primary care, and studies find their outcomes match physician care for comparable cases.",
      chart: { type: "line", unit: "K NPs", labels: ["2010", "2015", "2020", "2025"], values: [106, 205, 290, 385], caption: "licensed nurse practitioners in the U.S." },
      src: { n: "American Association of Nurse Practitioners", u: "https://www.aanp.org" } },
    { t: "Twelve hours, more errors", tone: "blind",
      s: "Nurses working shifts of 12.5 hours or longer are about 3 times more likely to report making an error than nurses on 8.5-hour shifts.",
      chart: { type: "bar", unit: "relative risk", labels: ["8.5h shift", "12.5h+ shift"], values: [1, 3], caption: "odds of self-reported error" },
      src: { n: "Health Affairs", u: "https://www.healthaffairs.org" } }
  ]
},
{
  id: "dentist", name: "Dentist",
  stats: [
    { t: "Decay nobody treats", tone: "blind",
      s: "More than 1 in 4 U.S. adults is walking around with untreated tooth decay right now.",
      chart: { type: "donut", value: 26, unit: "%", caption: "of adults with untreated cavities" },
      src: { n: "CDC Oral Health Surveillance Report", u: "https://www.cdc.gov/oralhealth" } },
    { t: "The uninsured mouth", tone: "blind",
      s: "Roughly 68 million American adults have no dental insurance, far more than lack medical coverage.",
      chart: { type: "bar", unit: "M adults", labels: ["No dental coverage", "No medical coverage"], values: [68, 26], caption: "uninsured U.S. adults" },
      src: { n: "CareQuest Institute for Oral Health", u: "https://www.carequest.org" } },
    { t: "Water that works", tone: "bright",
      s: "Community water fluoridation reduces tooth decay by about 25% and is ranked among the ten great public health achievements of the 20th century.",
      chart: { type: "donut", value: 25, unit: "%", caption: "reduction in decay from fluoridation" },
      src: { n: "Centers for Disease Control and Prevention", u: "https://www.cdc.gov/fluoridation" } },
    { t: "The ER is not a dental office", tone: "blind",
      s: "Americans make about 2 million emergency room visits a year for dental conditions the ER mostly cannot treat, costing over $2 billion.",
      chart: { type: "line", unit: "M visits", labels: ["2000", "2010", "2018"], values: [1.1, 1.8, 2.0], caption: "U.S. ER visits for dental problems" },
      src: { n: "American Dental Association Health Policy Institute", u: "https://www.ada.org" } },
    { t: "Fear keeps them away", tone: "blind",
      s: "About 36% of people experience dental anxiety, and roughly 12% have fear severe enough to delay or avoid care entirely.",
      chart: { type: "bar", unit: "%", labels: ["Some anxiety", "Severe fear"], values: [36, 12], caption: "prevalence of dental fear" },
      src: { n: "National Library of Medicine / PubMed", u: "https://pubmed.ncbi.nlm.nih.gov" } },
    { t: "Same mouth, different plans", tone: "blind",
      s: "Studies that sent the same patient to multiple dentists found treatment plans ranging from nothing to thousands of dollars of recommended work.",
      chart: { type: "bar", unit: "$ proposed", labels: ["Lowest plan", "Median", "Highest plan"], values: [0, 1500, 8000], caption: "spread of treatment plans for one patient" },
      src: { n: "Journal of the American Dental Association", u: "https://jada.ada.org" } },
    { t: "The mouth-body link", tone: "bright",
      s: "Treating gum disease is associated with fewer hospitalizations and lower medical costs for patients with diabetes and heart disease.",
      chart: { type: "bar", unit: "%", labels: ["Diabetes care savings", "Heart disease savings"], values: [40, 11], caption: "lower annual medical costs after periodontal care" },
      src: { n: "American Journal of Preventive Medicine", u: "https://www.ajpmonline.org" } },
    { t: "Deserts without dentists", tone: "blind",
      s: "Nearly 60 million Americans live in areas with a federally designated shortage of dental providers.",
      chart: { type: "donut", value: 57, unit: "M", caption: "people in dental shortage areas" },
      src: { n: "Health Resources & Services Administration (HRSA)", u: "https://data.hrsa.gov" } }
  ]
},
{
  id: "pharmacist", name: "Pharmacist",
  stats: [
    { t: "Harm in the bottle", tone: "blind",
      s: "Medication errors injure an estimated 1.5 million Americans every year, and most are preventable.",
      chart: { type: "donut", value: 1.5, unit: "M", caption: "Americans harmed by medication errors yearly" },
      src: { n: "National Academies of Sciences (Institute of Medicine)", u: "https://www.nationalacademies.org" } },
    { t: "Half the pills go untaken", tone: "blind",
      s: "About 50% of medications for chronic disease are not taken as prescribed, driving roughly 125,000 preventable deaths a year in the U.S.",
      chart: { type: "donut", value: 50, unit: "%", caption: "of chronic medications not taken as prescribed" },
      src: { n: "World Health Organization / Annals of Internal Medicine", u: "https://www.acpjournals.org" } },
    { t: "The most reachable clinician", tone: "bright",
      s: "Nearly 90% of Americans live within 5 miles of a community pharmacy, closer than any other healthcare access point.",
      chart: { type: "donut", value: 89, unit: "%", caption: "of Americans within 5 miles of a pharmacy" },
      src: { n: "National Association of Chain Drug Stores", u: "https://www.nacds.org" } },
    { t: "Pharmacy deserts spread", tone: "blind",
      s: "Thousands of U.S. pharmacies have closed since 2018, and almost half of counties now contain a pharmacy desert.",
      chart: { type: "line", unit: "K stores", labels: ["2018", "2020", "2022", "2024"], values: [61.2, 60.1, 58.8, 56.5], caption: "U.S. retail pharmacies (approx.)" },
      src: { n: "American Pharmacists Association", u: "https://www.pharmacist.com" } },
    { t: "Shots in arms", tone: "bright",
      s: "Pharmacists and pharmacy teams administered the majority of U.S. COVID-19 vaccinations, over 300 million doses.",
      chart: { type: "donut", value: 300, unit: "M+", caption: "vaccine doses given at U.S. pharmacies" },
      src: { n: "CDC Federal Retail Pharmacy Program", u: "https://www.cdc.gov" } },
    { t: "Paying double", tone: "blind",
      s: "U.S. prescription drug prices average about 2.8 times what other wealthy countries pay for the same medicines.",
      chart: { type: "bar", unit: "index", labels: ["U.S.", "Other wealthy nations"], values: [278, 100], caption: "drug price index, other nations = 100" },
      src: { n: "RAND Corporation", u: "https://www.rand.org" } },
    { t: "The generic dividend", tone: "bright",
      s: "Generic and biosimilar medicines save the U.S. health system over $400 billion every year.",
      chart: { type: "line", unit: "$B/yr", labels: ["2012", "2016", "2020", "2023"], values: [217, 293, 338, 445], caption: "annual savings from generics" },
      src: { n: "Association for Accessible Medicines", u: "https://accessiblemeds.org" } },
    { t: "Speed over safety", tone: "blind",
      s: "In surveys, a majority of chain pharmacists say staffing and time pressure are high enough to put patients at risk of dispensing errors.",
      chart: { type: "donut", value: 75, unit: "%", caption: "of chain pharmacists citing unsafe workloads" },
      src: { n: "American Pharmacists Association workplace surveys", u: "https://www.pharmacist.com" } }
  ]
},
{
  id: "veterinarian", name: "Veterinarian",
  stats: [
    { t: "A profession at risk", tone: "blind",
      s: "Veterinarians die by suicide at roughly 2 to 3.5 times the rate of the general U.S. population.",
      chart: { type: "bar", unit: "relative", labels: ["General population", "Male vets", "Female vets"], values: [1, 2.1, 3.5], caption: "relative suicide rate" },
      src: { n: "CDC / Journal of the American Veterinary Medical Association", u: "https://www.avma.org" } },
    { t: "Economic euthanasia", tone: "blind",
      s: "In surveys, most veterinarians report having euthanized an animal because the owner could not afford treatment.",
      chart: { type: "donut", value: 28, unit: "%", caption: "of pet owners report a cost barrier to vet care" },
      src: { n: "AVMA / Access to Veterinary Care Coalition", u: "https://www.avma.org" } },
    { t: "Debt on a vet's salary", tone: "blind",
      s: "Veterinary graduates carry around $180,000 in average student debt against starting salaries near $100,000, one of the worst debt ratios in medicine.",
      chart: { type: "bar", unit: "$K", labels: ["Avg vet school debt", "Avg starting salary"], values: [180, 100], caption: "debt vs. first-year pay" },
      src: { n: "American Veterinary Medical Association", u: "https://www.avma.org" } },
    { t: "Sentinels for humanity", tone: "bright",
      s: "About 60% of known human infectious diseases and 75% of new ones originate in animals, putting vets on the front line of pandemic prevention.",
      chart: { type: "bar", unit: "%", labels: ["Known diseases", "Emerging diseases"], values: [60, 75], caption: "share that are zoonotic" },
      src: { n: "World Organisation for Animal Health / CDC One Health", u: "https://www.cdc.gov/onehealth" } },
    { t: "The shelter turnaround", tone: "bright",
      s: "U.S. shelter euthanasia has fallen from roughly 13 million animals a year in the 1970s to under 1 million today.",
      chart: { type: "line", unit: "M/yr", labels: ["1973", "1990", "2010", "2024"], values: [13, 6, 2.6, 0.7], caption: "shelter animals euthanized per year" },
      src: { n: "ASPCA / Best Friends Animal Society", u: "https://www.aspca.org" } },
    { t: "Antibiotics by the ton", tone: "blind",
      s: "About two-thirds of medically important antibiotics sold in the U.S. go to food animals rather than people, feeding resistance.",
      chart: { type: "bar", unit: "%", labels: ["Livestock", "Human medicine"], values: [65, 35], caption: "share of medically important antibiotic sales" },
      src: { n: "U.S. Food & Drug Administration", u: "https://www.fda.gov" } },
    { t: "Too few hands for paws", tone: "blind",
      s: "Industry projections warn of a shortfall of about 15,000 veterinarians by 2030 as pet ownership keeps climbing.",
      chart: { type: "line", unit: "% households", labels: ["1988", "2008", "2024"], values: [56, 62, 66], caption: "U.S. households with a pet" },
      src: { n: "Mars Veterinary Health / AVMA", u: "https://www.avma.org" } },
    { t: "Compassion fatigue", tone: "blind",
      s: "Around 1 in 3 veterinary professionals reports high burnout, with the cost of mental health support still rare in practices.",
      chart: { type: "donut", value: 33, unit: "%", caption: "of veterinary staff reporting burnout" },
      src: { n: "Merck Animal Health Veterinary Wellbeing Study", u: "https://www.merck-animal-health.com" } }
  ]
},
{
  id: "teacher", name: "Teacher (K-12)",
  stats: [
    { t: "Out of pocket", tone: "blind",
      s: "U.S. teachers spend an average of about $700 of their own money on classroom supplies every year, and almost all of them do it.",
      chart: { type: "donut", value: 94, unit: "%", caption: "of teachers who buy supplies with their own money" },
      src: { n: "National Center for Education Statistics / AdoptAClassroom", u: "https://nces.ed.gov" } },
    { t: "The pay penalty", tone: "blind",
      s: "Teachers earn about 26% less per week than similarly educated college graduates in other fields, the widest gap on record.",
      chart: { type: "line", unit: "% gap", labels: ["1996", "2005", "2015", "2023"], values: [6, 14, 19, 26.4], caption: "teacher weekly wage penalty" },
      src: { n: "Economic Policy Institute", u: "https://www.epi.org" } },
    { t: "The first five years", tone: "blind",
      s: "Roughly 44% of new teachers leave the profession within their first five years.",
      chart: { type: "line", unit: "% gone", labels: ["Year 1", "Year 2", "Year 3", "Year 5"], values: [10, 19, 28, 44], caption: "cumulative attrition of new teachers" },
      src: { n: "Ingersoll, University of Pennsylvania CPRE", u: "https://www.gse.upenn.edu" } },
    { t: "One great teacher", tone: "bright",
      s: "Replacing a low value-added teacher with an average one raises a single classroom's lifetime earnings by about $250,000.",
      chart: { type: "donut", value: 250, unit: "$K", caption: "lifetime earnings gain per classroom" },
      src: { n: "Chetty, Friedman & Rockoff, American Economic Review", u: "https://www.aeaweb.org" } },
    { t: "The unfinished recovery", tone: "blind",
      s: "Average U.S. students remain about half a grade level behind pre-pandemic math achievement, with the poorest districts furthest behind.",
      chart: { type: "bar", unit: "grade levels", labels: ["Low-poverty districts", "High-poverty districts"], values: [0.3, 0.7], caption: "learning still lost vs. 2019" },
      src: { n: "Education Recovery Scorecard, Harvard & Stanford", u: "https://educationrecoveryscorecard.org" } },
    { t: "More than academics", tone: "bright",
      s: "Attending a high-quality kindergarten classroom predicts higher earnings, college attendance, and retirement savings decades later.",
      chart: { type: "bar", unit: "% more", labels: ["College attendance", "Earnings at 27"], values: [10, 5], caption: "boost from a strong early classroom" },
      src: { n: "Chetty et al., Quarterly Journal of Economics", u: "https://academic.oup.com/qje" } },
    { t: "Homework's weak spot", tone: "blind",
      s: "Meta-analyses find homework has little to no achievement benefit in elementary school, despite the hours families spend on it.",
      chart: { type: "bar", unit: "correlation", labels: ["Elementary", "Middle", "High school"], values: [0.05, 0.15, 0.25], caption: "homework-achievement link by level" },
      src: { n: "Cooper et al., Review of Educational Research", u: "https://journals.sagepub.com" } },
    { t: "Thinking about the door", tone: "blind",
      s: "About 1 in 4 teachers says they are likely to leave the job by the end of the school year, double pre-pandemic levels.",
      chart: { type: "donut", value: 25, unit: "%", caption: "of teachers considering leaving" },
      src: { n: "RAND State of the American Teacher Survey", u: "https://www.rand.org" } }
  ]
},
{
  id: "professor", name: "Professor / Researcher",
  stats: [
    { t: "The adjunct majority", tone: "blind",
      s: "About 68% of U.S. faculty now work off the tenure track, many paid per course with no job security.",
      chart: { type: "line", unit: "%", labels: ["1987", "2003", "2021"], values: [47, 56, 68], caption: "share of faculty off the tenure track" },
      src: { n: "American Association of University Professors", u: "https://www.aaup.org" } },
    { t: "Half the findings vanish", tone: "blind",
      s: "When 100 published psychology studies were rerun, only 36% produced statistically significant results the second time.",
      chart: { type: "bar", unit: "%", labels: ["Original studies", "Replications"], values: [97, 36], caption: "share with significant results" },
      src: { n: "Open Science Collaboration, Science", u: "https://www.science.org" } },
    { t: "Lecturing fails more students", tone: "blind",
      s: "Students in traditional lecture courses are 1.5 times more likely to fail than students in active learning courses.",
      chart: { type: "bar", unit: "% fail", labels: ["Active learning", "Lecture"], values: [22, 34], caption: "failure rates in STEM courses" },
      src: { n: "Freeman et al., PNAS", u: "https://www.pnas.org" } },
    { t: "The degree still pays", tone: "bright",
      s: "A bachelor's degree is worth about $1.2 million in additional lifetime earnings over a high school diploma.",
      chart: { type: "bar", unit: "$M lifetime", labels: ["High school", "Bachelor's", "Professional"], values: [1.6, 2.8, 4.7], caption: "median lifetime earnings" },
      src: { n: "Georgetown University Center on Education and the Workforce", u: "https://cew.georgetown.edu" } },
    { t: "A trillion-dollar tab", tone: "blind",
      s: "Americans owe about $1.7 trillion in student loan debt, more than credit cards and auto loans.",
      chart: { type: "line", unit: "$T", labels: ["2006", "2012", "2018", "2024"], values: [0.5, 1.0, 1.5, 1.74], caption: "U.S. student debt outstanding" },
      src: { n: "Federal Reserve Bank of New York", u: "https://www.newyorkfed.org" } },
    { t: "The PhD funnel", tone: "blind",
      s: "Universities produce far more PhDs than faculty jobs; in many fields fewer than 1 in 5 doctorates ever lands a tenure-track post.",
      chart: { type: "bar", unit: "%", labels: ["Want academia", "Get tenure track"], values: [70, 18], caption: "PhD aspirations vs. outcomes" },
      src: { n: "National Science Foundation, Survey of Earned Doctorates", u: "https://www.nsf.gov" } },
    { t: "Research compounds", tone: "bright",
      s: "Economists estimate returns on public research and development of 30 to 100% per year, among the best investments governments make.",
      chart: { type: "bar", unit: "% return", labels: ["Stocks (avg)", "Public R&D (low)", "Public R&D (high)"], values: [10, 30, 100], caption: "estimated annual returns" },
      src: { n: "Federal Reserve Bank of Dallas / NBER", u: "https://www.nber.org" } },
    { t: "Everyone gets an A", tone: "blind",
      s: "The average U.S. college GPA has climbed from about 2.5 in 1960 to roughly 3.15 today, with A now the most common grade.",
      chart: { type: "line", unit: "GPA", labels: ["1960", "1980", "2000", "2015"], values: [2.5, 2.8, 3.0, 3.15], caption: "average undergraduate GPA" },
      src: { n: "Rojstaczer & Healy, Teachers College Record", u: "https://www.gradeinflation.com" } }
  ]
},
{
  id: "lawyer", name: "Lawyer",
  stats: [
    { t: "Justice rationed", tone: "blind",
      s: "Low-income Americans receive no or inadequate legal help for 92% of their substantial civil legal problems.",
      chart: { type: "donut", value: 92, unit: "%", caption: "of civil legal needs unmet or undermet" },
      src: { n: "Legal Services Corporation, Justice Gap Report", u: "https://www.lsc.gov" } },
    { t: "The vanishing trial", tone: "blind",
      s: "Roughly 97% of federal criminal convictions come from plea bargains rather than trials, so most defendants never see a jury.",
      chart: { type: "line", unit: "% pleas", labels: ["1980", "2000", "2022"], values: [81, 94, 97], caption: "convictions resolved by guilty plea" },
      src: { n: "Pew Research Center / U.S. Courts data", u: "https://www.pewresearch.org" } },
    { t: "The profession's quiet struggle", tone: "blind",
      s: "About 21% of practicing lawyers qualify as problem drinkers and 28% struggle with depression, far above national averages.",
      chart: { type: "bar", unit: "%", labels: ["Lawyers: problem drinking", "Adults overall"], values: [21, 7], caption: "prevalence comparison" },
      src: { n: "American Bar Association / Hazelden Betty Ford study", u: "https://www.americanbar.org" } },
    { t: "Wrong man, real years", tone: "blind",
      s: "More than 3,500 wrongfully convicted Americans have been exonerated since 1989 after losing a combined 32,000+ years to prison.",
      chart: { type: "line", unit: "exonerations", labels: ["1995", "2005", "2015", "2024"], values: [60, 130, 170, 250], caption: "exonerations per year (approx.)" },
      src: { n: "National Registry of Exonerations", u: "https://www.law.umich.edu/special/exoneration" } },
    { t: "Overloaded defenders", tone: "blind",
      s: "Public defenders in many states carry 2 to 5 times the maximum recommended caseload, leaving minutes per case.",
      chart: { type: "bar", unit: "cases/yr", labels: ["Recommended max", "Typical urban defender"], values: [150, 500], caption: "felony-equivalent caseloads" },
      src: { n: "RAND / National Public Defense Workload Study", u: "https://www.rand.org" } },
    { t: "Millions of free hours", tone: "bright",
      s: "U.S. lawyers report several million hours of pro bono work each year, with large-firm attorneys averaging over 50 hours each.",
      chart: { type: "donut", value: 54, unit: "hrs", caption: "average pro bono hours, large firms" },
      src: { n: "American Bar Association Pro Bono Survey", u: "https://www.americanbar.org" } },
    { t: "Contracts make economies", tone: "bright",
      s: "World Bank research links stronger contract enforcement and rule of law to measurably higher national income and investment.",
      chart: { type: "bar", unit: "index", labels: ["Weak rule of law", "Strong rule of law"], values: [100, 320], caption: "relative GDP per capita (illustrative)" },
      src: { n: "World Bank Worldwide Governance Indicators", u: "https://www.worldbank.org" } },
    { t: "Eyewitness error", tone: "blind",
      s: "Mistaken eyewitness identifications contributed to about 63% of wrongful convictions later overturned by DNA evidence.",
      chart: { type: "donut", value: 63, unit: "%", caption: "of DNA exonerations involving eyewitness error" },
      src: { n: "Innocence Project", u: "https://innocenceproject.org" } }
  ]
},
{
  id: "police", name: "Police Officer",
  stats: [
    { t: "Half the murders unsolved", tone: "blind",
      s: "U.S. police now clear only about half of murders, down from over 90% in the 1960s.",
      chart: { type: "line", unit: "% cleared", labels: ["1965", "1990", "2010", "2022"], values: [91, 67, 65, 52], caption: "homicide clearance rate" },
      src: { n: "FBI Uniform Crime Reporting Program", u: "https://www.fbi.gov" } },
    { t: "Most calls aren't crimes", tone: "blind",
      s: "Analyses of millions of 911 calls find only about 1% involve violent crime in progress; most involve traffic, disputes, and welfare checks.",
      chart: { type: "bar", unit: "%", labels: ["Violent crime", "Property", "Everything else"], values: [1, 11, 88], caption: "what 911 calls actually are" },
      src: { n: "Vera Institute of Justice", u: "https://www.vera.org" } },
    { t: "The long decline", tone: "bright",
      s: "U.S. violent crime has fallen by roughly half since its 1991 peak, one of the great underreported public safety wins.",
      chart: { type: "line", unit: "per 100K", labels: ["1991", "2000", "2010", "2023"], values: [758, 507, 405, 364], caption: "violent crime rate" },
      src: { n: "FBI Crime Data Explorer", u: "https://cde.ucr.cjis.gov" } },
    { t: "The perception gap", tone: "blind",
      s: "In 23 of the last 27 Gallup surveys, a majority of Americans said crime was rising nationally, even in years when it fell.",
      chart: { type: "bar", unit: "%", labels: ["Believe crime is up", "Years crime actually rose"], values: [77, 30], caption: "perception vs. reality (typical year)" },
      src: { n: "Gallup / Pew Research Center", u: "https://news.gallup.com" } },
    { t: "The unseen toll", tone: "blind",
      s: "More officers die by suicide most years than are killed in the line of duty.",
      chart: { type: "bar", unit: "deaths/yr", labels: ["Suicide", "Felonious line of duty"], values: [170, 60], caption: "officer deaths, typical recent year" },
      src: { n: "First H.E.L.P. / FBI LEOKA", u: "https://www.fbi.gov" } },
    { t: "Crimes nobody reports", tone: "blind",
      s: "Fewer than half of violent crimes and barely a third of property crimes are ever reported to police.",
      chart: { type: "bar", unit: "%", labels: ["Violent reported", "Property reported"], values: [45, 32], caption: "share of crimes reported" },
      src: { n: "Bureau of Justice Statistics, NCVS", u: "https://bjs.ojp.gov" } },
    { t: "Hot spots work", tone: "bright",
      s: "Reviews of dozens of randomized studies find focused patrols at high-crime micro-locations reduce crime without simply pushing it next door.",
      chart: { type: "bar", unit: "effect", labels: ["Crime at hot spots", "Displacement found"], values: [-16, 0], caption: "median effect of hot-spot policing (%)" },
      src: { n: "Campbell Collaboration systematic review", u: "https://www.campbellcollaboration.org" } },
    { t: "Twenty million stops", tone: "blind",
      s: "The traffic stop is the single most common way Americans encounter police, around 20 million drivers a year.",
      chart: { type: "donut", value: 20, unit: "M", caption: "drivers stopped per year" },
      src: { n: "Stanford Open Policing Project", u: "https://openpolicing.stanford.edu" } }
  ]
},
{
  id: "firefighter", name: "Firefighter",
  stats: [
    { t: "Mostly medics now", tone: "blind",
      s: "About 65% of U.S. fire department calls are medical emergencies; actual fires are under 4%.",
      chart: { type: "bar", unit: "%", labels: ["Medical", "False alarms", "Fires", "Other"], values: [65, 8, 4, 23], caption: "fire department call types" },
      src: { n: "National Fire Protection Association", u: "https://www.nfpa.org" } },
    { t: "The cancer in the gear", tone: "blind",
      s: "Firefighters face a 9% higher cancer diagnosis rate and 14% higher cancer death rate than the general population, and the IARC classifies the occupation as carcinogenic.",
      chart: { type: "bar", unit: "% vs avg", labels: ["Diagnosis", "Death"], values: [9, 14], caption: "elevated cancer risk" },
      src: { n: "NIOSH / International Agency for Research on Cancer", u: "https://www.cdc.gov/niosh" } },
    { t: "The quiet victory", tone: "bright",
      s: "U.S. home fire deaths have fallen by more than half since 1980 thanks to smoke alarms, codes, and safer products.",
      chart: { type: "line", unit: "deaths/yr", labels: ["1980", "1995", "2010", "2023"], values: [5200, 3640, 2640, 2890], caption: "home fire deaths" },
      src: { n: "National Fire Protection Association", u: "https://www.nfpa.org" } },
    { t: "Hearts under load", tone: "blind",
      s: "Sudden cardiac events cause about 40 to 45% of on-duty firefighter deaths, more than flames do.",
      chart: { type: "donut", value: 43, unit: "%", caption: "of on-duty deaths from cardiac events" },
      src: { n: "U.S. Fire Administration", u: "https://www.usfa.fema.gov" } },
    { t: "The volunteer cliff", tone: "blind",
      s: "About 65% of U.S. firefighters are volunteers, and their numbers per capita have been falling for three decades while call volume tripled.",
      chart: { type: "line", unit: "per 1K people", labels: ["1987", "2000", "2020"], values: [3.4, 3.0, 2.4], caption: "volunteer firefighters per capita" },
      src: { n: "National Volunteer Fire Council", u: "https://www.nvfc.org" } },
    { t: "A burning West", tone: "blind",
      s: "Annual U.S. acres burned by wildfire have roughly doubled since the 1990s, stretching crews built for structure fires.",
      chart: { type: "line", unit: "M acres", labels: ["1990s avg", "2000s avg", "2010s avg", "2020-24 avg"], values: [3.3, 6.9, 7.5, 7.7], caption: "acres burned per year" },
      src: { n: "National Interagency Fire Center", u: "https://www.nifc.gov" } },
    { t: "Alarms beat engines", tone: "bright",
      s: "Working smoke alarms cut the risk of dying in a home fire by about 60%, saving more lives than any response-time improvement.",
      chart: { type: "donut", value: 60, unit: "%", caption: "lower death risk with working alarms" },
      src: { n: "National Fire Protection Association", u: "https://www.nfpa.org" } },
    { t: "Forever chemicals, close to home", tone: "blind",
      s: "PFAS chemicals appear in firefighting foam and protective gear, and firefighters carry higher PFAS blood levels than the public.",
      chart: { type: "bar", unit: "relative", labels: ["General public", "Firefighters"], values: [1, 2], caption: "relative PFAS exposure (illustrative)" },
      src: { n: "National Institute for Occupational Safety and Health", u: "https://www.cdc.gov/niosh" } }
  ]
},
{
  id: "software", name: "Software Engineer",
  stats: [
    { t: "The trillion-dollar bug", tone: "blind",
      s: "Poor software quality cost the U.S. economy an estimated $2.4 trillion in a single year.",
      chart: { type: "donut", value: 2.4, unit: "$T", caption: "annual cost of poor software quality" },
      src: { n: "Consortium for Information & Software Quality (CISQ)", u: "https://www.it-cisq.org" } },
    { t: "Features nobody touches", tone: "blind",
      s: "Industry analyses have long found that a majority of built software features are rarely or never used.",
      chart: { type: "bar", unit: "%", labels: ["Rarely/never used", "Sometimes", "Often"], values: [64, 16, 20], caption: "feature usage in delivered software" },
      src: { n: "Standish Group CHAOS research", u: "https://www.standishgroup.com" } },
    { t: "Over budget, over time", tone: "blind",
      s: "Large IT projects run on average 45% over budget and 7% over schedule while delivering 56% less value than predicted.",
      chart: { type: "bar", unit: "%", labels: ["Budget overrun", "Value shortfall"], values: [45, 56], caption: "large IT project averages" },
      src: { n: "McKinsey & Company / University of Oxford", u: "https://www.mckinsey.com" } },
    { t: "The web is broken for millions", tone: "blind",
      s: "About 95% of the top one million website homepages have detectable accessibility failures, locking out users with disabilities.",
      chart: { type: "donut", value: 95, unit: "%", caption: "of top homepages with WCAG failures" },
      src: { n: "WebAIM Million report", u: "https://webaim.org/projects/million" } },
    { t: "Built on borrowed code", tone: "bright",
      s: "Open source components appear in about 96% of commercial codebases, an unprecedented act of global cooperation that powers nearly everything.",
      chart: { type: "donut", value: 96, unit: "%", caption: "of codebases containing open source" },
      src: { n: "Synopsys Open Source Security Report", u: "https://www.synopsys.com" } },
    { t: "The breach bill", tone: "blind",
      s: "The average corporate data breach now costs about $4.9 million, and most trace back to preventable engineering and process failures.",
      chart: { type: "line", unit: "$M", labels: ["2017", "2020", "2024"], values: [3.6, 3.9, 4.9], caption: "average cost of a data breach" },
      src: { n: "IBM Cost of a Data Breach Report", u: "https://www.ibm.com/security" } },
    { t: "Software ate productivity", tone: "bright",
      s: "Digital technology contributes a large share of U.S. productivity growth, and the software industry adds over $1.6 trillion to GDP.",
      chart: { type: "line", unit: "$T", labels: ["2014", "2018", "2022"], values: [1.07, 1.36, 1.66], caption: "software's value added to U.S. GDP" },
      src: { n: "BSA Foundation / U.S. Bureau of Economic Analysis", u: "https://www.bea.gov" } },
    { t: "Who writes the code", tone: "blind",
      s: "Women hold only about 20% of U.S. software engineering jobs, a share barely changed in a decade.",
      chart: { type: "line", unit: "%", labels: ["1990", "2010", "2024"], values: [31, 21, 20], caption: "women in software occupations" },
      src: { n: "U.S. Bureau of Labor Statistics", u: "https://www.bls.gov" } }
  ]
},
{
  id: "datascientist", name: "Data Scientist",
  stats: [
    { t: "Models that never ship", tone: "blind",
      s: "Industry surveys repeatedly find that most machine learning models, often estimated at 80% or more, never make it into production.",
      chart: { type: "donut", value: 80, unit: "%", caption: "of ML models never deployed" },
      src: { n: "Gartner / VentureBeat industry surveys", u: "https://www.gartner.com" } },
    { t: "Garbage in", tone: "blind",
      s: "Bad data costs U.S. businesses an estimated $3.1 trillion a year, and data scientists spend most of their time cleaning rather than modeling.",
      chart: { type: "bar", unit: "% of time", labels: ["Cleaning & prep", "Modeling", "Everything else"], values: [60, 20, 20], caption: "how data scientists spend their week" },
      src: { n: "IBM / Anaconda State of Data Science", u: "https://www.anaconda.com" } },
    { t: "Bias ships at scale", tone: "blind",
      s: "Commercial facial analysis systems misclassified darker-skinned women up to 34% of the time while erring under 1% for lighter-skinned men.",
      chart: { type: "bar", unit: "% error", labels: ["Lighter-skinned men", "Darker-skinned women"], values: [0.8, 34.7], caption: "gender classification error rates" },
      src: { n: "Buolamwini & Gebru, Gender Shades (MIT)", u: "https://www.media.mit.edu" } },
    { t: "Most experiments change nothing", tone: "blind",
      s: "At companies that A/B test rigorously, only about a third of ideas produce a measurable positive effect, humbling for every roadmap.",
      chart: { type: "bar", unit: "%", labels: ["Positive", "No effect", "Negative"], values: [33, 41, 26], caption: "outcomes of online experiments" },
      src: { n: "Kohavi et al., Microsoft ExP research", u: "https://exp-platform.com" } },
    { t: "Anonymous isn't", tone: "blind",
      s: "About 87% of Americans can be uniquely identified from just their ZIP code, birth date, and sex.",
      chart: { type: "donut", value: 87, unit: "%", caption: "identifiable from 3 data points" },
      src: { n: "Latanya Sweeney, Harvard Data Privacy Lab", u: "https://dataprivacylab.org" } },
    { t: "Eyes that don't tire", tone: "bright",
      s: "Deep learning systems detect diabetic retinopathy and some cancers at accuracy matching or exceeding specialists, extending screening to clinics with no specialist at all.",
      chart: { type: "bar", unit: "% accuracy", labels: ["Specialists", "AI screening"], values: [91, 94], caption: "diabetic retinopathy detection (illustrative)" },
      src: { n: "JAMA / Nature Medicine", u: "https://jamanetwork.com" } },
    { t: "Forecasts got good", tone: "bright",
      s: "A modern 5-day weather forecast is as accurate as a 1-day forecast was in 1980, saving lives and billions in logistics.",
      chart: { type: "line", unit: "% accuracy", labels: ["1981", "2000", "2020"], values: [60, 80, 90], caption: "5-day forecast skill" },
      src: { n: "NOAA / Nature", u: "https://www.noaa.gov" } },
    { t: "The replication tax", tone: "blind",
      s: "Surveys in Nature found 70% of researchers have failed to reproduce another scientist's results, and half failed to reproduce their own.",
      chart: { type: "bar", unit: "%", labels: ["Failed others' results", "Failed own results"], values: [70, 50], caption: "researchers reporting failed replications" },
      src: { n: "Nature reproducibility survey", u: "https://www.nature.com" } }
  ]
},
{
  id: "electrical", name: "Electrical Engineer",
  stats: [
    { t: "The aging grid", tone: "blind",
      s: "The average U.S. electricity customer now loses power for about 5.5 hours a year, roughly double the interruption time of 2013.",
      chart: { type: "line", unit: "hours", labels: ["2013", "2017", "2021", "2023"], values: [3.0, 4.0, 5.5, 5.5], caption: "average annual outage duration" },
      src: { n: "U.S. Energy Information Administration", u: "https://www.eia.gov" } },
    { t: "The LED revolution", tone: "bright",
      s: "LED lighting uses about 75% less energy and lasts 25 times longer than incandescent bulbs, one of the fastest efficiency wins in history.",
      chart: { type: "bar", unit: "% energy", labels: ["Incandescent", "CFL", "LED"], values: [100, 30, 25], caption: "energy use for equal light" },
      src: { n: "U.S. Department of Energy", u: "https://www.energy.gov" } },
    { t: "A mountain of e-waste", tone: "blind",
      s: "The world generated 62 million tonnes of electronic waste in 2022, and less than a quarter was formally recycled.",
      chart: { type: "line", unit: "Mt", labels: ["2010", "2016", "2022", "2030 proj."], values: [34, 44, 62, 82], caption: "global e-waste generated" },
      src: { n: "UN Global E-waste Monitor", u: "https://ewastemonitor.info" } },
    { t: "One island, every chip", tone: "blind",
      s: "Around 90% of the world's most advanced semiconductors are fabricated by a single company in Taiwan.",
      chart: { type: "donut", value: 90, unit: "%", caption: "of leading-edge chips from one fab company" },
      src: { n: "Semiconductor Industry Association / CSIS", u: "https://www.semiconductors.org" } },
    { t: "Solar's price collapse", tone: "bright",
      s: "The cost of solar electricity has fallen about 90% since 2010, making it the cheapest electricity in history in many markets.",
      chart: { type: "line", unit: "$/MWh", labels: ["2010", "2015", "2020", "2024"], values: [378, 117, 50, 35], caption: "utility-scale solar cost" },
      src: { n: "Lazard Levelized Cost of Energy / IRENA", u: "https://www.lazard.com" } },
    { t: "Infrastructure report card", tone: "blind",
      s: "American infrastructure as a whole earns a C grade from civil and electrical engineers, with energy infrastructure flagged for chronic underinvestment.",
      chart: { type: "bar", unit: "grade (4=A)", labels: ["Rail", "Energy", "Roads", "Transit"], values: [2.3, 2.0, 1.7, 1.3], caption: "ASCE 2025 grades, numeric" },
      src: { n: "American Society of Civil Engineers Report Card", u: "https://infrastructurereportcard.org" } },
    { t: "Demand is back", tone: "blind",
      s: "After 15 flat years, U.S. electricity demand is forecast to grow about 15% by 2030, driven by data centers and electrification, faster than the grid is being built.",
      chart: { type: "line", unit: "TWh", labels: ["2010", "2020", "2024", "2030 proj."], values: [3886, 3856, 4070, 4700], caption: "U.S. electricity consumption" },
      src: { n: "U.S. Energy Information Administration", u: "https://www.eia.gov" } },
    { t: "Electrify everything", tone: "bright",
      s: "Electrifying transport and heating could cut U.S. greenhouse emissions by roughly 40% with technology that already exists.",
      chart: { type: "bar", unit: "% of emissions", labels: ["Transport", "Buildings", "Industry heat"], values: [28, 13, 23], caption: "emissions addressable by electrification" },
      src: { n: "U.S. EPA / Rewiring America", u: "https://www.epa.gov" } }
  ]
},
{
  id: "civil", name: "Civil Engineer",
  stats: [
    { t: "42,000 bad bridges", tone: "blind",
      s: "About 42,000 U.S. bridges are rated in poor condition, and Americans cross them 167 million times a day.",
      chart: { type: "donut", value: 6.8, unit: "%", caption: "of U.S. bridges rated structurally poor" },
      src: { n: "American Road & Transportation Builders Association", u: "https://artbabridgereport.org" } },
    { t: "More lanes, same jam", tone: "blind",
      s: "Adding highway capacity induces almost exactly proportional new driving; a 10% increase in lane miles yields about 10% more vehicle miles within a few years.",
      chart: { type: "bar", unit: "%", labels: ["Lane miles added", "New driving induced"], values: [10, 10], caption: "the fundamental law of road congestion" },
      src: { n: "Duranton & Turner, American Economic Review", u: "https://www.aeaweb.org" } },
    { t: "Roads that kill", tone: "blind",
      s: "About 40,000 Americans die on roads each year, a per-mile death rate far higher than peer nations that redesigned streets for safety.",
      chart: { type: "bar", unit: "per 100K", labels: ["U.S.", "Canada", "Germany", "Norway"], values: [12.8, 5.1, 3.7, 2.0], caption: "road deaths per 100,000 people" },
      src: { n: "National Highway Traffic Safety Administration / OECD", u: "https://www.nhtsa.gov" } },
    { t: "Water saved the century", tone: "bright",
      s: "Clean water systems explain nearly half of the total mortality decline in U.S. cities in the early 20th century, likely engineering's greatest life-saving feat.",
      chart: { type: "donut", value: 43, unit: "%", caption: "of urban mortality decline from water treatment" },
      src: { n: "Cutler & Miller, Demography", u: "https://www.nber.org" } },
    { t: "Megaproject math", tone: "blind",
      s: "Nine out of ten megaprojects run over budget, with rail projects averaging 45% overruns and benefits routinely overestimated.",
      chart: { type: "donut", value: 90, unit: "%", caption: "of megaprojects over budget" },
      src: { n: "Flyvbjerg, Oxford Saïd Business School", u: "https://www.sbs.ox.ac.uk" } },
    { t: "The dam clock", tone: "blind",
      s: "The average American dam is over 60 years old, and more than 2,200 high-hazard dams are rated deficient.",
      chart: { type: "bar", unit: "count", labels: ["High-hazard deficient dams", "Dams overall (K)"], values: [2200, 92], caption: "U.S. dam inventory snapshot" },
      src: { n: "Association of State Dam Safety Officials", u: "https://damsafety.org" } },
    { t: "Codes beat chaos", tone: "bright",
      s: "Every $1 invested in modern hazard-resistant building codes saves about $11 in avoided disaster losses.",
      chart: { type: "bar", unit: "$", labels: ["Invested", "Saved"], values: [1, 11], caption: "benefit-cost of modern codes" },
      src: { n: "National Institute of Building Sciences", u: "https://www.nibs.org" } },
    { t: "Concrete's shadow", tone: "blind",
      s: "Cement production alone accounts for about 8% of global CO2 emissions, more than every airline combined.",
      chart: { type: "bar", unit: "% global CO2", labels: ["Cement", "Aviation"], values: [8, 2.5], caption: "share of global emissions" },
      src: { n: "Chatham House / IEA", u: "https://www.chathamhouse.org" } }
  ]
}
);
