/* =========================================================================
   BlindSpots 2026 — dataset, part 2 of 2 (professions 16–30).
   Same shape as part 1. See blindspots-data-1.js for the format notes.
   ========================================================================= */

window.BLINDSPOTS = window.BLINDSPOTS || [];

window.BLINDSPOTS.push(
{
  id: "architect", name: "Architect",
  stats: [
    { t: "Buildings are the climate", tone: "blind",
      s: "Buildings account for about 39% of global energy-related carbon emissions, counting construction and operations.",
      chart: { type: "bar", unit: "%", labels: ["Building operations", "Materials & construction", "Everything else"], values: [28, 11, 61], caption: "global energy-related CO2" },
      src: { n: "World Green Building Council / IEA", u: "https://worldgbc.org" } },
    { t: "Designing for 1 in 4", tone: "blind",
      s: "More than 1 in 4 U.S. adults lives with a disability, yet most buildings still treat accessibility as a code minimum rather than a design driver.",
      chart: { type: "donut", value: 27, unit: "%", caption: "of U.S. adults with a disability" },
      src: { n: "Centers for Disease Control and Prevention", u: "https://www.cdc.gov" } },
    { t: "The missing homes", tone: "blind",
      s: "The U.S. is short roughly 3.8 million homes, a gap built over decades of underbuilding relative to household growth.",
      chart: { type: "line", unit: "M homes", labels: ["2012", "2016", "2020"], values: [2.5, 3.3, 3.8], caption: "estimated U.S. housing shortfall" },
      src: { n: "Freddie Mac", u: "https://www.freddiemac.com" } },
    { t: "A window heals", tone: "bright",
      s: "Hospital patients with a window view of nature recovered faster and needed less pain medication than identical patients facing a wall.",
      chart: { type: "bar", unit: "days", labels: ["View of trees", "View of wall"], values: [7.96, 8.7], caption: "post-surgery hospital stay" },
      src: { n: "Ulrich, Science", u: "https://www.science.org" } },
    { t: "Two percent", tone: "blind",
      s: "Only about 2% of licensed U.S. architects are Black, a share that has barely moved in 40 years.",
      chart: { type: "bar", unit: "%", labels: ["Black architects", "Black U.S. population"], values: [2, 14], caption: "representation gap" },
      src: { n: "National Council of Architectural Registration Boards", u: "https://www.ncarb.org" } },
    { t: "Green pays rent", tone: "bright",
      s: "Certified green buildings command rent premiums around 6% and sale premiums over 7% while cutting energy costs.",
      chart: { type: "bar", unit: "% premium", labels: ["Rent", "Sale price"], values: [6, 7.6], caption: "green-certified building premiums" },
      src: { n: "Journal of Sustainable Real Estate / USGBC", u: "https://www.usgbc.org" } },
    { t: "The 2030 gap", tone: "blind",
      s: "Architecture firms that signed the 2030 carbon commitment are averaging about 50% emissions reduction against a 100% target due this decade.",
      chart: { type: "bar", unit: "%", labels: ["Current average", "2030 target"], values: [50, 100], caption: "portfolio emissions reduction" },
      src: { n: "AIA 2030 Commitment Report", u: "https://www.aia.org" } },
    { t: "Heat by design", tone: "bright",
      s: "Cool roofs and urban greening can lower neighborhood temperatures several degrees, and design choices decide who survives heat waves.",
      chart: { type: "bar", unit: "°F hotter", labels: ["Tree-covered blocks", "Bare asphalt blocks"], values: [0, 7], caption: "urban heat island spread within one city" },
      src: { n: "U.S. EPA Heat Island Program", u: "https://www.epa.gov/heatislands" } }
  ]
},
{
  id: "banker", name: "Investment Banker",
  stats: [
    { t: "Wall Street buys Main Street", tone: "blind",
      s: "Investor purchases reached roughly 1 in 4 single-family homes sold in recent years, while the median U.S. home price nearly doubled in a decade.",
      chart: { type: "line", unit: "$K", labels: ["2012", "2016", "2020", "2024"], values: [225, 310, 390, 420], caption: "median U.S. home sale price" },
      src: { n: "CoreLogic / U.S. Census Bureau", u: "https://www.census.gov" } },
    { t: "Most mergers fail", tone: "blind",
      s: "Studies place the failure rate of mergers and acquisitions at 70 to 90%, yet deal volume keeps setting records.",
      chart: { type: "donut", value: 75, unit: "%", caption: "of M&A deals that destroy value (midpoint)" },
      src: { n: "Harvard Business Review", u: "https://hbr.org" } },
    { t: "Money left on the table", tone: "blind",
      s: "IPOs underprice by about 17% on average on day one, transferring billions from issuing companies to allocated clients every year.",
      chart: { type: "donut", value: 17, unit: "%", caption: "average first-day IPO pop" },
      src: { n: "Jay Ritter, University of Florida IPO data", u: "https://site.warrington.ufl.edu/ritter" } },
    { t: "The index always wins", tone: "blind",
      s: "About 90% of actively managed U.S. equity funds underperform the S&P 500 over 15 years, after fees.",
      chart: { type: "bar", unit: "%", labels: ["1 year", "5 years", "15 years"], values: [60, 78, 90], caption: "active funds losing to the index" },
      src: { n: "S&P Dow Jones SPIVA Scorecard", u: "https://www.spglobal.com/spdji" } },
    { t: "The crisis bill", tone: "blind",
      s: "The 2008 financial crisis cost every American an estimated $70,000 in lifetime income.",
      chart: { type: "donut", value: 70, unit: "$K", caption: "lifetime income lost per American" },
      src: { n: "Federal Reserve Bank of San Francisco", u: "https://www.frbsf.org" } },
    { t: "Capital builds things", tone: "bright",
      s: "Companies that access public markets through IPOs generate over 90% of their job growth after going public.",
      chart: { type: "bar", unit: "% job growth", labels: ["Before IPO", "After IPO"], values: [8, 92], caption: "employment growth timing at IPO firms" },
      src: { n: "Kenan Institute / IHS Global Insight", u: "https://kenaninstitute.unc.edu" } },
    { t: "The 100-hour week", tone: "blind",
      s: "Junior bankers in a leaked Goldman Sachs survey reported 98-hour average weeks and collapsing physical and mental health.",
      chart: { type: "bar", unit: "hrs/week", labels: ["U.S. average", "First-year analysts"], values: [38, 98], caption: "weekly working hours" },
      src: { n: "Goldman Sachs analyst survey, reported by Reuters", u: "https://www.reuters.com" } },
    { t: "Banking the unbanked", tone: "bright",
      s: "The share of adults worldwide with a financial account jumped from 51% to 76% in a decade, one of development's quietest wins.",
      chart: { type: "line", unit: "%", labels: ["2011", "2014", "2017", "2021"], values: [51, 62, 69, 76], caption: "adults with a financial account" },
      src: { n: "World Bank Global Findex", u: "https://www.worldbank.org/globalfindex" } }
  ]
},
{
  id: "advisor", name: "Financial Advisor",
  stats: [
    { t: "The 1% that eats 28%", tone: "blind",
      s: "A 1% annual fee consumes roughly a quarter of a portfolio's potential value over a 40-year career.",
      chart: { type: "bar", unit: "$K final", labels: ["0.25% fee", "1% fee"], values: [98, 77], caption: "value of $10K after 40 yrs at 7% (illustrative)" },
      src: { n: "U.S. Securities and Exchange Commission, investor bulletins", u: "https://www.investor.gov" } },
    { t: "The behavior gap", tone: "blind",
      s: "Investors earn about 1.1% per year less than the very funds they own by buying high and selling low.",
      chart: { type: "bar", unit: "% return", labels: ["Fund return", "Investor return"], values: [7.3, 6.2], caption: "10-year annualized, dollar-weighted" },
      src: { n: "Morningstar, Mind the Gap study", u: "https://www.morningstar.com" } },
    { t: "Advice that pays for itself", tone: "bright",
      s: "Vanguard estimates good behavioral coaching alone adds up to 2% a year in net returns, more than typical advisory fees.",
      chart: { type: "bar", unit: "% added/yr", labels: ["Behavioral coaching", "Asset location", "Rebalancing"], values: [2.0, 0.6, 0.35], caption: "sources of advisor value" },
      src: { n: "Vanguard Advisor's Alpha research", u: "https://advisors.vanguard.com" } },
    { t: "Conflicted advice", tone: "blind",
      s: "Conflicts of interest in retirement advice were estimated to cost American savers about $17 billion every year.",
      chart: { type: "donut", value: 17, unit: "$B/yr", caption: "cost of conflicted retirement advice" },
      src: { n: "White House Council of Economic Advisers", u: "https://obamawhitehouse.archives.gov" } },
    { t: "Three questions, half fail", tone: "blind",
      s: "Only about a third of Americans can correctly answer three basic questions on interest, inflation, and diversification.",
      chart: { type: "donut", value: 30, unit: "%", caption: "answering all three correctly" },
      src: { n: "Lusardi & Mitchell, Global Financial Literacy Excellence Center", u: "https://gflec.org" } },
    { t: "The $400 problem", tone: "blind",
      s: "About 37% of U.S. adults could not cover a $400 emergency expense with cash or its equivalent.",
      chart: { type: "donut", value: 37, unit: "%", caption: "unable to cover a $400 emergency in cash" },
      src: { n: "Federal Reserve, Survey of Household Economics (SHED)", u: "https://www.federalreserve.gov" } },
    { t: "Retirement, unfunded", tone: "blind",
      s: "The median retirement account for Americans aged 55 to 64 holds about $185,000, far short of what their target income requires.",
      chart: { type: "bar", unit: "$K", labels: ["Median saved (55-64)", "Common target"], values: [185, 1000], caption: "retirement savings vs. rule-of-thumb need" },
      src: { n: "Federal Reserve, Survey of Consumer Finances", u: "https://www.federalreserve.gov" } },
    { t: "The fee revolution", tone: "bright",
      s: "Average fund fees have fallen by more than half since 2000, saving investors billions per year, a win driven by indexing and fee pressure.",
      chart: { type: "line", unit: "% avg fee", labels: ["2000", "2010", "2023"], values: [0.99, 0.83, 0.36], caption: "asset-weighted average fund expense ratio" },
      src: { n: "Investment Company Institute / Morningstar", u: "https://www.ici.org" } }
  ]
},
{
  id: "accountant", name: "Accountant / CPA",
  stats: [
    { t: "Audits with findings", tone: "blind",
      s: "PCAOB inspectors found deficiencies in about 46% of the audits they reviewed in a recent cycle.",
      chart: { type: "line", unit: "%", labels: ["2020", "2021", "2022", "2023"], values: [29, 34, 40, 46], caption: "inspected audits with Part I.A deficiencies" },
      src: { n: "Public Company Accounting Oversight Board", u: "https://pcaobus.org" } },
    { t: "The empty pipeline", tone: "blind",
      s: "The number of CPA exam candidates has fallen by about a third from its peak while three-quarters of current CPAs near retirement.",
      chart: { type: "line", unit: "K candidates", labels: ["2016", "2019", "2022", "2024"], values: [102, 75, 67, 64], caption: "new CPA exam candidates" },
      src: { n: "AICPA Trends Report", u: "https://www.aicpa-cima.com" } },
    { t: "The $688 billion gap", tone: "blind",
      s: "The IRS estimates Americans underpay taxes by about $688 billion a year, more than the entire defense budget's discretionary increase debates.",
      chart: { type: "donut", value: 688, unit: "$B/yr", caption: "estimated gross tax gap" },
      src: { n: "Internal Revenue Service", u: "https://www.irs.gov" } },
    { t: "6.5 billion hours", tone: "blind",
      s: "Americans spend about 6.5 billion hours a year on tax paperwork, the equivalent of 3 million full-time jobs.",
      chart: { type: "donut", value: 6.5, unit: "B hrs", caption: "annual hours spent on tax compliance" },
      src: { n: "National Taxpayer Advocate, IRS", u: "https://www.taxpayeradvocate.irs.gov" } },
    { t: "Fraud's 5% tax", tone: "blind",
      s: "Organizations lose an estimated 5% of revenue to fraud each year, and tips catch far more of it than audits do.",
      chart: { type: "bar", unit: "% detected by", labels: ["Tips", "Internal audit", "External audit"], values: [43, 14, 3], caption: "how occupational fraud is found" },
      src: { n: "Association of Certified Fraud Examiners", u: "https://www.acfe.com" } },
    { t: "Clean books, cheap capital", tone: "bright",
      s: "Audited financial statements measurably lower borrowing costs for private companies, often by enough to pay for the audit several times over.",
      chart: { type: "bar", unit: "bps", labels: ["Unaudited", "Audited"], values: [100, 31], caption: "relative interest spread (illustrative)" },
      src: { n: "Journal of Accounting Research", u: "https://onlinelibrary.wiley.com/journal/1475679x" } },
    { t: "Earnings, managed", tone: "blind",
      s: "Surveyed CFOs estimated that in any year about 20% of public companies manage earnings, misstating profits by around 10%.",
      chart: { type: "donut", value: 20, unit: "%", caption: "of firms managing reported earnings" },
      src: { n: "Dichev, Graham, Harvey & Rajgopal, Duke/Emory survey", u: "https://www.fuqua.duke.edu" } },
    { t: "Small business lifeline", tone: "bright",
      s: "A large majority of small business failures involve cash-flow problems, exactly the area where basic accounting help measurably extends survival.",
      chart: { type: "donut", value: 82, unit: "%", caption: "of failures involving cash-flow trouble" },
      src: { n: "U.S. Bank study / SCORE", u: "https://www.score.org" } }
  ]
},
{
  id: "realestate", name: "Real Estate Agent",
  stats: [
    { t: "The agent's own house", tone: "blind",
      s: "When agents sell their own homes, they leave them on the market about 10 days longer and sell for 3.7% more than client homes.",
      chart: { type: "bar", unit: "% premium", labels: ["Client's home", "Agent's own home"], values: [0, 3.7], caption: "sale price difference" },
      src: { n: "Levitt & Syverson, Review of Economics and Statistics", u: "https://www.nber.org" } },
    { t: "The 6% question", tone: "blind",
      s: "U.S. real estate commissions long averaged 5 to 6%, double or triple the rates in most wealthy countries, until the 2024 NAR settlement began to crack the structure.",
      chart: { type: "bar", unit: "%", labels: ["U.S.", "U.K.", "Netherlands"], values: [5.5, 1.3, 1.5], caption: "typical total commission" },
      src: { n: "U.S. Department of Justice filings / academic comparisons", u: "https://www.justice.gov" } },
    { t: "Wealth on a foundation", tone: "bright",
      s: "The median homeowner holds about $400,000 in net worth versus roughly $10,000 for the median renter.",
      chart: { type: "bar", unit: "$K", labels: ["Homeowner", "Renter"], values: [396, 10], caption: "median household net worth" },
      src: { n: "Federal Reserve, Survey of Consumer Finances", u: "https://www.federalreserve.gov" } },
    { t: "38 years old, first keys", tone: "blind",
      s: "The median first-time homebuyer is now 38 years old, the oldest ever recorded; in 1981 it was 29.",
      chart: { type: "line", unit: "age", labels: ["1981", "2000", "2015", "2024"], values: [29, 31, 32, 38], caption: "median age of first-time buyers" },
      src: { n: "National Association of Realtors", u: "https://www.nar.realtor" } },
    { t: "Steering still happens", tone: "blind",
      s: "Paired-testing investigations found agents showed minority buyers fewer listings and steered them toward different neighborhoods at significant rates.",
      chart: { type: "donut", value: 49, unit: "%", caption: "of tests showing unequal treatment (Newsday probe)" },
      src: { n: "Newsday Long Island investigation / HUD studies", u: "https://www.hud.gov" } },
    { t: "Denied at the bank", tone: "blind",
      s: "Black mortgage applicants are denied at roughly double the rate of white applicants with similar incomes.",
      chart: { type: "bar", unit: "% denied", labels: ["White applicants", "Black applicants"], values: [7, 16], caption: "conventional mortgage denial rates" },
      src: { n: "Home Mortgage Disclosure Act data, CFPB", u: "https://www.consumerfinance.gov" } },
    { t: "Roots and neighbors", tone: "bright",
      s: "Homeowners move less, vote more, and report stronger community ties, stability effects that ripple far beyond the sale.",
      chart: { type: "bar", unit: "% voting", labels: ["Renters", "Homeowners"], values: [49, 67], caption: "local election participation (illustrative)" },
      src: { n: "Harvard Joint Center for Housing Studies", u: "https://www.jchs.harvard.edu" } },
    { t: "Locked in place", tone: "blind",
      s: "With most owners holding sub-4% mortgages, existing-home sales fell to their lowest level since 1995, freezing the ladder for everyone below.",
      chart: { type: "line", unit: "M sales", labels: ["2021", "2022", "2023", "2024"], values: [6.1, 5.0, 4.1, 4.06], caption: "existing-home sales per year" },
      src: { n: "National Association of Realtors", u: "https://www.nar.realtor" } }
  ]
},
{
  id: "insurance", name: "Insurance Agent",
  stats: [
    { t: "The protection gap", tone: "blind",
      s: "About 60% of global natural catastrophe losses carry no insurance at all, leaving families and governments holding the bill.",
      chart: { type: "donut", value: 60, unit: "%", caption: "of disaster losses uninsured worldwide" },
      src: { n: "Swiss Re Institute", u: "https://www.swissre.com" } },
    { t: "Flooded without coverage", tone: "blind",
      s: "Only about 4% of U.S. homeowners hold flood insurance, while 90% of natural disasters involve flooding.",
      chart: { type: "bar", unit: "%", labels: ["Have flood insurance", "Disasters involving flood"], values: [4, 90], caption: "the flood coverage mismatch" },
      src: { n: "FEMA National Flood Insurance Program", u: "https://www.fema.gov" } },
    { t: "Underinsured when it burns", tone: "blind",
      s: "After major wildfires, roughly two-thirds of surveyed homeowners discovered their coverage fell short of rebuilding costs.",
      chart: { type: "donut", value: 66, unit: "%", caption: "of wildfire victims underinsured" },
      src: { n: "United Policyholders post-disaster surveys", u: "https://uphelp.org" } },
    { t: "Medical debt's shadow", tone: "blind",
      s: "Medical issues contribute to about two-thirds of U.S. personal bankruptcies, even among people who had insurance.",
      chart: { type: "donut", value: 66, unit: "%", caption: "of bankruptcies involving medical issues" },
      src: { n: "American Journal of Public Health", u: "https://ajph.aphapublications.org" } },
    { t: "The industry that crash-tests", tone: "bright",
      s: "Insurer-funded crash testing and safety advocacy helped cut U.S. road deaths per mile by about 80% since 1975.",
      chart: { type: "line", unit: "per 100M mi", labels: ["1975", "1995", "2015", "2023"], values: [3.35, 1.73, 1.15, 1.26], caption: "deaths per 100 million vehicle miles" },
      src: { n: "Insurance Institute for Highway Safety", u: "https://www.iihs.org" } },
    { t: "Retreat from risk", tone: "blind",
      s: "Major insurers have paused or pulled home coverage in California and Florida as climate losses mount, pushing millions toward bare-bones state plans.",
      chart: { type: "line", unit: "K policies", labels: ["2019", "2021", "2023", "2025"], values: [200, 400, 1200, 1500], caption: "Florida Citizens (state insurer) policy growth, approx." },
      src: { n: "Florida Office of Insurance Regulation / NAIC", u: "https://www.floir.com" } },
    { t: "Life cover at half-mast", tone: "blind",
      s: "Barely half of American adults own life insurance, down from 63% in 2011, and the coverage gap is widest for families who need it most.",
      chart: { type: "line", unit: "%", labels: ["2011", "2016", "2021", "2024"], values: [63, 59, 52, 51], caption: "adults with life insurance" },
      src: { n: "LIMRA Insurance Barometer", u: "https://www.limra.com" } },
    { t: "Rebuilt because insured", tone: "bright",
      s: "Insured households recover from disasters dramatically faster, with insurance payouts the single strongest predictor of rebuilding.",
      chart: { type: "bar", unit: "% rebuilt in 4 yrs", labels: ["Underinsured", "Fully insured"], values: [45, 80], caption: "rebuilding after disaster (illustrative)" },
      src: { n: "Wharton Risk Management Center", u: "https://riskcenter.wharton.upenn.edu" } }
  ]
},
{
  id: "marketing", name: "Marketing Manager",
  stats: [
    { t: "The fraud tax", tone: "blind",
      s: "Digital ad fraud siphons an estimated $80 to 100 billion a year, much of it billed to brands as genuine engagement.",
      chart: { type: "line", unit: "$B/yr", labels: ["2018", "2021", "2024"], values: [35, 65, 100], caption: "estimated global ad fraud losses" },
      src: { n: "Juniper Research", u: "https://www.juniperresearch.com" } },
    { t: "The eBay experiment", tone: "blind",
      s: "When eBay switched off paid search ads in controlled tests, sales barely moved; most clicks came from people who would have bought anyway.",
      chart: { type: "bar", unit: "% of sales", labels: ["Attributed to ads", "Actually caused by ads"], values: [5, 0.5], caption: "brand search ad effectiveness" },
      src: { n: "Blake, Nosko & Tadelis, Econometrica", u: "https://www.econometricsociety.org" } },
    { t: "Most launches die", tone: "blind",
      s: "Roughly 75 to 85% of new consumer packaged goods fail within their first year on the shelf.",
      chart: { type: "donut", value: 80, unit: "%", caption: "of new CPG products failing in year one" },
      src: { n: "Nielsen / Harvard Business School", u: "https://www.nielsen.com" } },
    { t: "Banner blindness is real", tone: "blind",
      s: "Average display ad click-through rates sit around 0.1%, one click per thousand views.",
      chart: { type: "donut", value: 0.1, unit: "%", caption: "average display ad CTR" },
      src: { n: "Google Display Benchmarks / Smart Insights", u: "https://www.smartinsights.com" } },
    { t: "Brand compounds", tone: "bright",
      s: "Long-term brand building drives larger and more durable sales effects than short-term activation, with the best results near a 60/40 budget split.",
      chart: { type: "bar", unit: "% budget", labels: ["Brand building", "Sales activation"], values: [60, 40], caption: "optimal long/short split" },
      src: { n: "Binet & Field, IPA", u: "https://ipa.co.uk" } },
    { t: "Dark patterns ship daily", tone: "blind",
      s: "A crawl of 11,000 shopping sites found dark patterns on about 11% of them, with the most popular sites the worst offenders.",
      chart: { type: "donut", value: 11, unit: "%", caption: "of shopping sites using dark patterns" },
      src: { n: "Mathur et al., Princeton University", u: "https://www.cs.princeton.edu" } },
    { t: "Privacy's trust deficit", tone: "blind",
      s: "About 79% of Americans say they are concerned about how companies use their data, and most feel they have no control over it.",
      chart: { type: "donut", value: 79, unit: "%", caption: "concerned about corporate data use" },
      src: { n: "Pew Research Center", u: "https://www.pewresearch.org" } },
    { t: "Ads pay for the internet", tone: "bright",
      s: "The ad-supported internet underwrites most free search, maps, email, and journalism, an implicit subsidy worth thousands of dollars per user per year.",
      chart: { type: "bar", unit: "$/user/yr", labels: ["What users pay", "Estimated value received"], values: [0, 1400], caption: "value of free ad-funded services (illustrative)" },
      src: { n: "MIT Sloan digital economy research", u: "https://mitsloan.mit.edu" } }
  ]
},
{
  id: "sales", name: "Salesperson",
  stats: [
    { t: "They decided before you called", tone: "blind",
      s: "B2B buyers complete somewhere between 57 and 70% of their purchase research before ever talking to a sales rep.",
      chart: { type: "donut", value: 65, unit: "%", caption: "of the buying journey done before first contact" },
      src: { n: "Gartner (CEB) buyer research", u: "https://www.gartner.com" } },
    { t: "Half miss the number", tone: "blind",
      s: "In most years, only 40 to 60% of sales reps hit their full quota.",
      chart: { type: "donut", value: 53, unit: "%", caption: "average quota attainment rate" },
      src: { n: "Salesforce State of Sales / CSO Insights", u: "https://www.salesforce.com" } },
    { t: "The revolving door", tone: "blind",
      s: "Sales teams turn over around 27 to 35% of their people each year, roughly triple the all-industry average, resetting customer relationships constantly.",
      chart: { type: "bar", unit: "%/yr", labels: ["All industries", "Sales teams"], values: [11, 31], caption: "annual employee turnover" },
      src: { n: "Harvard Business Review / Bridge Group", u: "https://hbr.org" } },
    { t: "Talk less, win more", tone: "bright",
      s: "Analysis of millions of recorded sales calls found top performers speak only about 43% of the time and let buyers do the rest.",
      chart: { type: "bar", unit: "% talking", labels: ["Top reps", "Average reps"], values: [43, 65], caption: "rep talk-time on winning vs. losing calls" },
      src: { n: "Gong Research Labs", u: "https://www.gong.io" } },
    { t: "Trust starts underwater", tone: "blind",
      s: "Only about 3% of buyers say they consider salespeople trustworthy, a hole every honest rep digs out of daily.",
      chart: { type: "donut", value: 3, unit: "%", caption: "of buyers who rate salespeople trustworthy" },
      src: { n: "HubSpot Research", u: "https://www.hubspot.com" } },
    { t: "Speed wins the lead", tone: "bright",
      s: "Responding to an inquiry within an hour makes a meaningful qualification conversation about 7 times more likely than waiting a day.",
      chart: { type: "bar", unit: "relative odds", labels: ["Within 1 hour", "After 24 hours"], values: [7, 1], caption: "odds of qualifying the lead" },
      src: { n: "Harvard Business Review lead response study", u: "https://hbr.org" } },
    { t: "The disappearing storefront rep", tone: "blind",
      s: "E-commerce has climbed from 4% to over 16% of U.S. retail in 15 years, structurally shrinking traditional sales roles.",
      chart: { type: "line", unit: "% of retail", labels: ["2010", "2015", "2020", "2024"], values: [4.2, 7.2, 14, 16.2], caption: "e-commerce share of U.S. retail" },
      src: { n: "U.S. Census Bureau", u: "https://www.census.gov" } },
    { t: "Selling runs the economy", tone: "bright",
      s: "Roughly 1 in 9 American workers works in sales, and nothing in the economy moves until somebody sells it.",
      chart: { type: "donut", value: 11, unit: "%", caption: "of U.S. workers in sales occupations" },
      src: { n: "U.S. Bureau of Labor Statistics", u: "https://www.bls.gov" } }
  ]
},
{
  id: "hr", name: "HR Manager",
  stats: [
    { t: "The interview illusion", tone: "blind",
      s: "Unstructured interviews predict job performance barely better than a coin flip, yet they remain the most common hiring tool.",
      chart: { type: "bar", unit: "validity", labels: ["Unstructured interview", "Structured interview", "Work sample"], values: [0.20, 0.51, 0.54], caption: "predictive validity of selection methods" },
      src: { n: "Schmidt & Hunter, Psychological Bulletin", u: "https://www.apa.org" } },
    { t: "A name changes everything", tone: "blind",
      s: "Identical resumes with white-sounding names received about 50% more interview callbacks than those with Black-sounding names.",
      chart: { type: "bar", unit: "% callback", labels: ["Emily/Greg", "Lakisha/Jamal"], values: [10.1, 6.7], caption: "callback rates for identical resumes" },
      src: { n: "Bertrand & Mullainathan, American Economic Review", u: "https://www.aeaweb.org" } },
    { t: "Reviews rate the rater", tone: "blind",
      s: "More than half the variance in performance ratings reflects the rater's quirks rather than the employee's actual performance.",
      chart: { type: "bar", unit: "% of variance", labels: ["Rater quirks", "Actual performance", "Other"], values: [55, 21, 24], caption: "what performance ratings measure" },
      src: { n: "Scullen, Mount & Goff, Journal of Applied Psychology", u: "https://www.apa.org" } },
    { t: "Two-thirds checked out", tone: "blind",
      s: "Only about 33% of U.S. employees are engaged at work, and disengagement costs the world economy trillions in lost productivity.",
      chart: { type: "bar", unit: "%", labels: ["Engaged", "Not engaged", "Actively disengaged"], values: [33, 50, 17], caption: "U.S. employee engagement" },
      src: { n: "Gallup State of the Global Workplace", u: "https://www.gallup.com" } },
    { t: "The price of a goodbye", tone: "blind",
      s: "Replacing an employee typically costs one-half to two times their annual salary in hiring, ramp-up, and lost knowledge.",
      chart: { type: "bar", unit: "× salary", labels: ["Low estimate", "High estimate"], values: [0.5, 2], caption: "cost to replace one employee" },
      src: { n: "Gallup / SHRM", u: "https://www.shrm.org" } },
    { t: "Training that evaporates", tone: "blind",
      s: "Companies spend over $100 billion a year on training, yet studies suggest only a small fraction transfers into changed behavior on the job.",
      chart: { type: "bar", unit: "$B", labels: ["Spent on training", "Estimated to transfer"], values: [100, 25], caption: "U.S. training spend vs. behavior change" },
      src: { n: "Harvard Business Review / ATD", u: "https://hbr.org" } },
    { t: "Structure is fairness", tone: "bright",
      s: "Structured hiring with defined criteria roughly doubles predictive accuracy and measurably narrows demographic gaps at the same time.",
      chart: { type: "bar", unit: "validity", labels: ["Gut feel", "Structured process"], values: [0.2, 0.45], caption: "hiring accuracy, unstructured vs. structured" },
      src: { n: "Schmidt & Hunter / Harvard Kennedy School", u: "https://www.hks.harvard.edu" } },
    { t: "Onboarding pays twice", tone: "bright",
      s: "Strong onboarding programs are associated with dramatically higher retention and faster productivity for new hires.",
      chart: { type: "bar", unit: "% retained", labels: ["Weak onboarding", "Strong onboarding"], values: [50, 82], caption: "new-hire retention comparison" },
      src: { n: "Brandon Hall Group / Glassdoor research", u: "https://www.brandonhall.com" } }
  ]
},
{
  id: "journalist", name: "Journalist",
  stats: [
    { t: "News deserts spread", tone: "blind",
      s: "The U.S. has lost about a third of its newspapers since 2005, and over 200 counties now have no local news outlet at all.",
      chart: { type: "line", unit: "K papers", labels: ["2005", "2014", "2024"], values: [8.9, 7.1, 5.6], caption: "U.S. newspapers remaining" },
      src: { n: "Northwestern Medill State of Local News", u: "https://localnewsinitiative.northwestern.edu" } },
    { t: "Trust at the bottom", tone: "blind",
      s: "Only about 31% of Americans say they trust mass media to report fully and fairly, near the lowest ever measured.",
      chart: { type: "line", unit: "%", labels: ["1976", "2000", "2015", "2024"], values: [72, 51, 40, 31], caption: "trust in mass media" },
      src: { n: "Gallup", u: "https://news.gallup.com" } },
    { t: "Half the newsroom gone", tone: "blind",
      s: "U.S. newsroom employment has fallen about 26% since 2008, with newspaper newsrooms cut by more than half.",
      chart: { type: "line", unit: "K jobs", labels: ["2008", "2014", "2020"], values: [114, 94, 85], caption: "newsroom employees" },
      src: { n: "Pew Research Center", u: "https://www.pewresearch.org" } },
    { t: "Lies travel faster", tone: "blind",
      s: "False news on social platforms spreads about 6 times faster than true news and reaches far more people.",
      chart: { type: "bar", unit: "relative speed", labels: ["True stories", "False stories"], values: [1, 6], caption: "speed of diffusion on Twitter" },
      src: { n: "Vosoughi, Roy & Aral, Science (MIT)", u: "https://www.science.org" } },
    { t: "Watchdogs save money", tone: "bright",
      s: "When a local newspaper closes, municipal borrowing costs rise measurably; scrutiny was quietly saving taxpayers millions.",
      chart: { type: "bar", unit: "bps", labels: ["Paper in town", "After closure"], values: [0, 10], caption: "rise in municipal bond yields post-closure" },
      src: { n: "Gao, Lee & Murphy, Journal of Financial Economics", u: "https://www.sciencedirect.com" } },
    { t: "Investigations pay for themselves", tone: "bright",
      s: "The Panama Papers investigation has helped governments recover more than $1.3 billion in unpaid taxes and fines worldwide.",
      chart: { type: "donut", value: 1.3, unit: "$B+", caption: "recovered after one investigation" },
      src: { n: "International Consortium of Investigative Journalists", u: "https://www.icij.org" } },
    { t: "Crime up, coverage misleads", tone: "blind",
      s: "Crime consistently dominates local coverage out of proportion to its actual incidence, helping explain why majorities believe crime rises even when it falls.",
      chart: { type: "bar", unit: "%", labels: ["Crime share of coverage", "Crime share of daily life"], values: [25, 1], caption: "salience gap (illustrative)" },
      src: { n: "Pew Research Center / news content analyses", u: "https://www.pewresearch.org" } },
    { t: "Paid like a teacher, sued like a bank", tone: "blind",
      s: "The median U.S. reporter earns about $60,000 a year while legal threats against journalists have risen sharply.",
      chart: { type: "donut", value: 60, unit: "$K", caption: "median reporter salary" },
      src: { n: "U.S. Bureau of Labor Statistics", u: "https://www.bls.gov" } }
  ]
},
{
  id: "chef", name: "Chef / Restaurateur",
  stats: [
    { t: "The 90% myth", tone: "bright",
      s: "Contrary to legend, only about 17% of restaurants fail in their first year; the oft-quoted 90% figure has no basis in the data.",
      chart: { type: "bar", unit: "% closed", labels: ["Year 1 (myth)", "Year 1 (actual)", "Year 5 (actual)"], values: [90, 17, 50], caption: "restaurant survival, myth vs. measured" },
      src: { n: "Luo & Stark, U.S. Bureau of Labor Statistics data", u: "https://www.bls.gov" } },
    { t: "Three cents on the dollar", tone: "blind",
      s: "The average restaurant keeps a profit margin of only 3 to 5%, so a single bad month can erase a quarter's earnings.",
      chart: { type: "bar", unit: "% margin", labels: ["Restaurants", "Retail avg", "Software"], values: [4, 7, 20], caption: "typical net margins by industry" },
      src: { n: "National Restaurant Association", u: "https://restaurant.org" } },
    { t: "The $2.13 wage", tone: "blind",
      s: "The federal tipped minimum wage has been frozen at $2.13 an hour since 1991, and tipped workers face roughly double the poverty rate.",
      chart: { type: "bar", unit: "$/hr", labels: ["Tipped minimum", "Federal minimum"], values: [2.13, 7.25], caption: "federal wage floors" },
      src: { n: "U.S. Department of Labor / EPI", u: "https://www.dol.gov" } },
    { t: "One in six get sick", tone: "blind",
      s: "About 48 million Americans, 1 in 6, get a foodborne illness every year, and restaurant practices are a leading control point.",
      chart: { type: "donut", value: 48, unit: "M/yr", caption: "Americans sickened by food annually" },
      src: { n: "Centers for Disease Control and Prevention", u: "https://www.cdc.gov/foodsafety" } },
    { t: "Everyone's first job", tone: "bright",
      s: "One in three Americans had their first job in a restaurant, making kitchens the country's biggest informal job-training program.",
      chart: { type: "donut", value: 33, unit: "%", caption: "of Americans whose first job was in food service" },
      src: { n: "National Restaurant Association", u: "https://restaurant.org" } },
    { t: "Dinner's hidden landfill", tone: "blind",
      s: "U.S. restaurants generate an estimated 11.4 million tons of food waste a year, while up to 10% of food is wasted before it even reaches a plate.",
      chart: { type: "bar", unit: "M tons", labels: ["Restaurant waste", "Recycled/donated"], values: [11.4, 1.7], caption: "annual restaurant food waste" },
      src: { n: "ReFED / U.S. EPA", u: "https://refed.org" } },
    { t: "A full day's salt", tone: "blind",
      s: "The average chain restaurant entree plus sides delivers close to a full day's recommended sodium in a single meal.",
      chart: { type: "bar", unit: "mg sodium", labels: ["One restaurant meal", "Daily limit"], values: [2100, 2300], caption: "sodium in a typical chain meal" },
      src: { n: "CDC / Center for Science in the Public Interest", u: "https://www.cdc.gov/salt" } },
    { t: "The immigrant engine", tone: "bright",
      s: "Immigrants own a far larger share of restaurants than of businesses overall, making food the most common doorway to American entrepreneurship.",
      chart: { type: "bar", unit: "% immigrant-owned", labels: ["All businesses", "Restaurants"], values: [22, 37], caption: "immigrant ownership rates" },
      src: { n: "Migration Policy Institute / Census Bureau data", u: "https://www.migrationpolicy.org" } }
  ]
},
{
  id: "farmer", name: "Farmer",
  stats: [
    { t: "The water bill", tone: "blind",
      s: "Agriculture accounts for about 70% of global freshwater withdrawals, more than all cities and industry combined.",
      chart: { type: "bar", unit: "%", labels: ["Agriculture", "Industry", "Municipal"], values: [70, 19, 11], caption: "global freshwater withdrawals" },
      src: { n: "UN Food and Agriculture Organization", u: "https://www.fao.org" } },
    { t: "Five times the corn", tone: "bright",
      s: "U.S. corn yields have grown more than fivefold since 1940 on roughly the same land, feeding billions from the same acres.",
      chart: { type: "line", unit: "bu/acre", labels: ["1940", "1970", "2000", "2024"], values: [29, 72, 137, 179], caption: "U.S. corn yield per acre" },
      src: { n: "USDA National Agricultural Statistics Service", u: "https://www.nass.usda.gov" } },
    { t: "The off-farm paycheck", tone: "blind",
      s: "The median U.S. farm household earns essentially all of its income off the farm; farming itself often loses money in median years.",
      chart: { type: "bar", unit: "$K", labels: ["Off-farm income", "Farm income (median)"], values: [82, -1], caption: "median farm household income sources" },
      src: { n: "USDA Economic Research Service", u: "https://www.ers.usda.gov" } },
    { t: "58 years old", tone: "blind",
      s: "The average American farmer is about 58 years old, and farmers over 65 outnumber those under 35 by more than 4 to 1.",
      chart: { type: "line", unit: "avg age", labels: ["1982", "2002", "2022"], values: [50.5, 55.3, 58.1], caption: "average age of U.S. farmers" },
      src: { n: "USDA Census of Agriculture", u: "https://www.nass.usda.gov" } },
    { t: "Losing the ground itself", tone: "blind",
      s: "Researchers estimate about a third of the Midwest Corn Belt has lost its carbon-rich topsoil entirely, eroded faster than it can ever reform.",
      chart: { type: "donut", value: 35, unit: "%", caption: "of Corn Belt land with topsoil gone" },
      src: { n: "University of Massachusetts, PNAS", u: "https://www.pnas.org" } },
    { t: "Subsidies flow uphill", tone: "blind",
      s: "The largest 10% of farm operations collect well over two-thirds of federal commodity payments.",
      chart: { type: "bar", unit: "% of payments", labels: ["Top 10% of farms", "Other 90%"], values: [70, 30], caption: "distribution of farm subsidies" },
      src: { n: "Environmental Working Group Farm Subsidy Database", u: "https://farm.ewg.org" } },
    { t: "Farming's carbon plate", tone: "blind",
      s: "Agriculture produces about 10% of U.S. greenhouse gas emissions, with livestock methane the single biggest slice.",
      chart: { type: "bar", unit: "% of U.S. GHG", labels: ["Agriculture", "Transportation", "Power"], values: [10, 28, 25], caption: "U.S. emissions by sector" },
      src: { n: "U.S. Environmental Protection Agency", u: "https://www.epa.gov" } },
    { t: "No-till takes root", tone: "bright",
      s: "Conservation tillage practices now cover most U.S. cropland acres, cutting erosion dramatically on every acre converted.",
      chart: { type: "line", unit: "% of acres", labels: ["1990", "2005", "2020"], values: [26, 41, 56], caption: "cropland under conservation tillage" },
      src: { n: "USDA Economic Research Service", u: "https://www.ers.usda.gov" } }
  ]
},
{
  id: "construction", name: "Construction Manager",
  stats: [
    { t: "The productivity puzzle", tone: "blind",
      s: "Construction labor productivity has barely grown in 50 years while manufacturing productivity multiplied several times over.",
      chart: { type: "line", unit: "index", labels: ["1970", "1990", "2010", "2020"], values: [100, 103, 99, 104], caption: "construction productivity (1970 = 100)" },
      src: { n: "McKinsey Global Institute / U.S. BEA", u: "https://www.mckinsey.com" } },
    { t: "One in five", tone: "blind",
      s: "Construction accounts for about 1 in 5 U.S. workplace deaths, with falls the leading cause year after year.",
      chart: { type: "bar", unit: "% of deaths", labels: ["Falls", "Struck-by", "Electrocution", "Caught-between"], values: [38, 8, 7, 5], caption: "construction's fatal four" },
      src: { n: "OSHA / U.S. Bureau of Labor Statistics", u: "https://www.osha.gov" } },
    { t: "80% over, 20 months late", tone: "blind",
      s: "Large construction projects typically run up to 80% over budget and 20 months behind schedule.",
      chart: { type: "bar", unit: "%", labels: ["Budget overrun", "On-time delivery"], values: [80, 25], caption: "large project performance" },
      src: { n: "McKinsey & Company", u: "https://www.mckinsey.com" } },
    { t: "Half a million missing hands", tone: "blind",
      s: "The U.S. construction industry needs roughly half a million more workers than it can find, slowing housing and infrastructure alike.",
      chart: { type: "donut", value: 500, unit: "K", caption: "estimated worker shortfall" },
      src: { n: "Associated Builders and Contractors", u: "https://www.abc.org" } },
    { t: "Twice the trash", tone: "blind",
      s: "Construction and demolition debris totals about 600 million tons a year in the U.S., double all municipal household garbage combined.",
      chart: { type: "bar", unit: "M tons/yr", labels: ["C&D debris", "Municipal waste"], values: [600, 292], caption: "U.S. annual waste streams" },
      src: { n: "U.S. Environmental Protection Agency", u: "https://www.epa.gov" } },
    { t: "The factory-built future", tone: "bright",
      s: "Modular construction can compress project schedules by 20 to 50% and is finally scaling in housing and healthcare.",
      chart: { type: "bar", unit: "% time saved", labels: ["Traditional build", "Modular build"], values: [0, 35], caption: "schedule compression from modular methods" },
      src: { n: "McKinsey & Company", u: "https://www.mckinsey.com" } },
    { t: "A silent crisis on site", tone: "blind",
      s: "Construction has one of the highest suicide rates of any U.S. industry, several times the rate of workplace fatalities themselves.",
      chart: { type: "bar", unit: "per 100K", labels: ["All workers", "Construction workers"], values: [32, 56], caption: "male suicide rate by industry" },
      src: { n: "CDC Morbidity and Mortality Weekly Report", u: "https://www.cdc.gov/mmwr" } },
    { t: "Building codes pay 11 to 1", tone: "bright",
      s: "Every dollar spent meeting modern building codes returns about $11 in avoided disaster damage, a return most investments never touch.",
      chart: { type: "bar", unit: "$", labels: ["Cost", "Benefit"], values: [1, 11], caption: "modern code benefit-cost ratio" },
      src: { n: "National Institute of Building Sciences", u: "https://www.nibs.org" } }
  ]
},
{
  id: "pilot", name: "Pilot",
  stats: [
    { t: "The safest era ever", tone: "bright",
      s: "The fatality risk on commercial flights has fallen to roughly 1 per 13 million passenger boardings, making this the safest period in aviation history.",
      chart: { type: "line", unit: "per M flights", labels: ["1970", "1990", "2010", "2023"], values: [6.4, 1.9, 0.6, 0.08], caption: "fatal accidents per million flights" },
      src: { n: "MIT / International Air Transport Association", u: "https://www.iata.org" } },
    { t: "The human factor", tone: "blind",
      s: "Human error contributes to roughly 70 to 80% of aviation accidents, which is why training, not technology, remains the frontier.",
      chart: { type: "donut", value: 75, unit: "%", caption: "of accidents involving human error" },
      src: { n: "FAA Human Factors research", u: "https://www.faa.gov" } },
    { t: "The checklist that left the cockpit", tone: "bright",
      s: "Aviation's crew checklists, adapted to surgery by the WHO, cut surgical deaths by nearly half in pilot hospitals.",
      chart: { type: "bar", unit: "% mortality", labels: ["Before checklist", "After checklist"], values: [1.5, 0.8], caption: "surgical death rate with WHO checklist" },
      src: { n: "New England Journal of Medicine", u: "https://www.nejm.org" } },
    { t: "Not enough pilots", tone: "blind",
      s: "Forecasts call for over 600,000 new pilots needed worldwide over 20 years, and regional U.S. airlines already park planes for lack of crews.",
      chart: { type: "donut", value: 649, unit: "K", caption: "new pilots needed by 2043" },
      src: { n: "Boeing Pilot and Technician Outlook", u: "https://www.boeing.com" } },
    { t: "Skills going soft", tone: "blind",
      s: "Regulators have warned that heavy reliance on automation is eroding pilots' manual flying skills, a factor in several fatal accidents.",
      chart: { type: "bar", unit: "% of flight", labels: ["Autopilot engaged", "Hand-flown"], values: [95, 5], caption: "typical airline flight time" },
      src: { n: "FAA Safety Alert / NTSB", u: "https://www.ntsb.gov" } },
    { t: "A heavy contrail", tone: "blind",
      s: "Aviation produces about 2.5% of global CO2, and roughly 1% of the world's population causes about half of aviation's emissions.",
      chart: { type: "bar", unit: "%", labels: ["Frequent flyers (1%)", "Everyone else"], values: [50, 50], caption: "share of aviation emissions" },
      src: { n: "Global Environmental Change / ICCT", u: "https://theicct.org" } },
    { t: "Tired at the yoke", tone: "blind",
      s: "Pilot fatigue is cited as a contributing factor in roughly 1 in 5 incidents reported to NASA's aviation safety system.",
      chart: { type: "donut", value: 20, unit: "%", caption: "of incident reports citing fatigue" },
      src: { n: "NASA Aviation Safety Reporting System", u: "https://asrs.arc.nasa.gov" } },
    { t: "Small planes, big risk", tone: "blind",
      s: "General aviation's fatal accident rate is dozens of times higher per hour than the airlines, a gap passengers rarely appreciate.",
      chart: { type: "bar", unit: "per 100K hrs", labels: ["Airlines", "General aviation"], values: [0.01, 0.95], caption: "fatal accidents per 100,000 flight hours" },
      src: { n: "National Transportation Safety Board", u: "https://www.ntsb.gov" } }
  ]
},
{
  id: "socialworker", name: "Social Worker",
  stats: [
    { t: "Caseloads off the chart", tone: "blind",
      s: "Child welfare caseworkers routinely carry double the recommended caseload, and annual turnover runs 20 to 40%.",
      chart: { type: "bar", unit: "cases", labels: ["Recommended", "Typical reality"], values: [15, 31], caption: "children per caseworker" },
      src: { n: "Child Welfare League of America", u: "https://www.cwla.org" } },
    { t: "Aging out into nothing", tone: "blind",
      s: "About 20% of youth who age out of foster care become homeless almost immediately, and fewer than 1 in 20 earns a bachelor's degree.",
      chart: { type: "bar", unit: "%", labels: ["Instantly homeless", "Earn bachelor's"], values: [20, 4], caption: "outcomes for youth aging out" },
      src: { n: "National Foster Youth Institute", u: "https://nfyi.org" } },
    { t: "One in seven children", tone: "blind",
      s: "An estimated 1 in 7 U.S. children experienced abuse or neglect in the past year, most of it never reaching any agency.",
      chart: { type: "donut", value: 14, unit: "%", caption: "of children experiencing maltreatment yearly" },
      src: { n: "CDC Child Abuse & Neglect Prevention", u: "https://www.cdc.gov" } },
    { t: "Housing First works", tone: "bright",
      s: "Housing First programs keep about 80% of chronically homeless participants stably housed while cutting emergency service costs.",
      chart: { type: "bar", unit: "% housed", labels: ["Treatment first", "Housing First"], values: [45, 80], caption: "stable housing at follow-up" },
      src: { n: "National Alliance to End Homelessness / HUD", u: "https://endhomelessness.org" } },
    { t: "Seven dollars back", tone: "bright",
      s: "High-quality early childhood intervention returns roughly $7 or more for every $1 invested through better health, earnings, and lower crime.",
      chart: { type: "bar", unit: "$", labels: ["Invested", "Returned"], values: [1, 7], caption: "return on early childhood programs" },
      src: { n: "Heckman Equation, University of Chicago", u: "https://heckmanequation.org" } },
    { t: "Paid less than the need", tone: "blind",
      s: "The median social worker earns about $58,000 a year, often while carrying graduate debt comparable to a lawyer's.",
      chart: { type: "bar", unit: "$K", labels: ["Median salary", "Typical MSW debt"], values: [58, 66], caption: "pay vs. graduate debt" },
      src: { n: "U.S. Bureau of Labor Statistics / CSWE", u: "https://www.bls.gov" } },
    { t: "Crisis calls answered differently", tone: "bright",
      s: "Civilian crisis-response teams like CAHOOTS resolve tens of thousands of calls a year, requesting police backup in under 2% of cases.",
      chart: { type: "donut", value: 2, unit: "%", caption: "of crisis calls needing police backup" },
      src: { n: "White Bird Clinic CAHOOTS program data", u: "https://whitebirdclinic.org" } },
    { t: "The trauma they carry", tone: "blind",
      s: "Around 70% of child welfare workers show at least mild symptoms of secondary traumatic stress from the cases they absorb.",
      chart: { type: "donut", value: 70, unit: "%", caption: "of workers with secondary traumatic stress" },
      src: { n: "Journal of Traumatic Stress / NCTSN", u: "https://www.nctsn.org" } }
  ]
}
);
